transmission:
  image: ghcr.io/viranch/transmission
  restart: always
  net: "container:tordash"
  environment:
    PUSHOVER_APP_TOKEN: ''
    PUSHOVER_USER_KEY: ''
    HOSTNAME: myserver
  volumes:
    - /opt/tv/transmission:/data

jackett:
  image:  ghcr.io/viranch/jackett
  image: lscr.io/linuxserver/jackett
  restart: always
  net: "container:tordash"
  environment:
    PUID: 0
    PGID: 0
    TZ: Etc/UTC # adjust this
    AUTO_UPDATE: "true"
  volumes:
    - /opt/tv/jackett:/config

tordash:
  image: ghcr.io/viranch/tordash
  restart: always
  container_name: tordash
  environment:
    AUTH_USER: ''
    AUTH_PASS: ''
  ports:
    - "80:80"
  volumes:
    - /opt/tv/transmission/downloads:/data:ro
    - /opt/tv/jackett:/jackett:ro
